# Generated by Django 5.2.15 on 2026-06-29 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_type', models.PositiveIntegerField(choices=[(1, 'Midterm'), (2, 'Final'), (3, 'Quiz'), (4, 'Practical')])),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_entries', to='students.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_entries', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'start_time'], name='timetable_e_date_1adc2d_idx'), models.Index(fields=['klass', 'date'], name='timetable_e_klass_i_60dd09_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='students.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['day_of_week', 'start_time'], name='timetable_t_day_of__776898_idx'), models.Index(fields=['teacher', 'day_of_week'], name='timetable_t_teacher_8a0654_idx'), models.Index(fields=['klass', 'day_of_week'], name='timetable_t_klass_i_9f52ba_idx')],
            },
        ),
    ]
