# Generated by Django 5.2.15 on 2026-06-29 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('section_name', models.CharField(max_length=10)),
                ('threshold_percent', models.PositiveIntegerField(default=75)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'unique_together': {('department', 'year', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('klass', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.class')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roll_number'],
                'indexes': [models.Index(fields=['roll_number'], name='students_st_roll_nu_6ff92b_idx'), models.Index(fields=['department', 'year'], name='students_st_departm_c0447e_idx')],
            },
        ),
    ]
